server:
  port: 8083
  servlet:
    context-path=/restaurant-service:

springdoc:
  swagger-ui:
    path: /docs/swagger-ui


spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql=true:

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:restaurantDB}?allowPublicKeyRetrieval=true&useSSL=false
    # url: jdbc:mysql://host.docker.internal:3307/restaurantDB
    username: restaurantUser
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver